import {api,ApiError} from './api';
import {currentUser} from './auth';
import {escape,roles,availability,field,area,options,split,limited,shell,bindForm} from './ui';
interface Developer {id:number;displayName:string|null;description?:string|null;role:string|null;technologies:string[];experienceYears:number|null;githubUrl?:string|null;availability:string|null;hourlyRate:number|null}
interface Project {id:number;title:string;description:string;summary:string|null;roles:string[];createdAt:string;ownerId?:number}
interface Page<T>{content:T[];number:number;totalPages:number;totalElements:number}
export interface Draft {description:string;summary:string;roles:string[];tasks:string[];existingStack:string[]}
let draft:Draft|null=null;
export function setDraft(value:Draft){draft=value;}
function failure(root:HTMLElement,e:unknown,retry:()=>void){if(!root.isConnected)return;root.innerHTML=`<div class="empty"><p role="alert">${escape(e instanceof Error?e.message:'Cererea a eșuat.')}</p>${e instanceof ApiError&&e.status===401?'<a class="auth register" href="/login">Login</a>':'<button class="auth register" id="retry">Încearcă din nou</button>'}</div>`;root.querySelector('#retry')?.addEventListener('click',retry);}
const initials=(name:string)=>name.trim().split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase()||'?';
const skeleton=(count:number,label:string)=>`<p class="sr-only" role="status">${escape(label)}</p><div class="skeleton-list" aria-hidden="true">${'<div class="skeleton-card"><span></span><span></span><span></span></div>'.repeat(count)}</div>`;
function devCard(d:Developer){const name=d.displayName||'Profil fără nume';return `<article class="dev-card"><header><span class="dev-avatar">${escape(initials(name))}</span><div><h3><a href="/developers/${d.id}">${escape(name)}</a></h3><span class="dev-role">${escape(roles[d.role||'']||'Client')}</span></div></header><span class="dev-availability ${escape(d.availability||'unknown')}">${escape(availability[d.availability||'']||'Disponibilitate nespecificată')}</span><div class="tags">${d.technologies.slice(0,6).map(t=>`<span>${escape(t)}</span>`).join('')}</div><footer><p>${d.experienceYears==null?'Experiență nespecificată':`${d.experienceYears} ani experiență`}<br><strong>${d.hourlyRate==null?'Tarif nespecificat':`$${escape(d.hourlyRate)} pe oră`}</strong></p>${currentUser()?.id!==d.id?`<a class="auth login" href="/chat/${d.id}">Trimite mesaj</a>`:''}</footer></article>`;}
export async function renderBasic(root:HTMLElement,path:string,navigate:(p:string)=>void){root.innerHTML='<p role="status">Se încarcă…</p>';try{
 if(path==='/profile'){
  let d:Partial<Developer>={};try{d=await api<Developer>('/me/profile');}catch(e){if(!(e instanceof ApiError&&e.status===404))throw e;}if(!root.isConnected)return;
  shell(root,'Profilul meu','Prezintă-te și spune ce poți aduce unui proiect.',`<form class="editor">${field('Nume afișat','displayName',d.displayName,'required maxlength="100"')}${area('Despre tine','description',d.description,'maxlength="2000"')}<div class="form-grid"><div class="field"><label for="role">Rol de programator (opțional pentru client)</label><select id="role" name="role">${options(roles,d.role||'','Client / nespecificat')}</select></div><div class="field"><label for="availability">Disponibilitate</label><select id="availability" name="availability">${options(availability,d.availability||'','Nespecificată')}</select></div>${field('Experiență (ani)','experienceYears',d.experienceYears,'type="number" min="0" max="60" step="1"')}${field('Tarif (dolari pe oră)','hourlyRate',d.hourlyRate,'type="number" min="0" max="99999999.99" step="0.01"')}</div>${field('Tehnologii, separate prin virgulă','technologies',d.technologies?.join(', '),'placeholder="TypeScript, React, Spring"')}${field('Profil GitHub','githubUrl',d.githubUrl,'type="url" maxlength="255" placeholder="https://github.com/numele-tau"')}<p class="hint">Fără tarif nou, valoarea salvată rămâne. Tariful este în dolari pe oră (USD).</p><button class="auth register" type="submit">Salvează profilul</button><p role="status" aria-live="polite"></p></form>`);
  bindForm(root,async f=>{const v=(n:string)=>String(f.get(n)||'').trim();const github=v('githubUrl');if(github&&!/^https:\/\/github\.com\/[^\s/]+(\/[^\s]*)?$/.test(github))throw new Error('Folosește un link https://github.com/numele-tau.');if(!github&&d.githubUrl)throw new Error('Păstrează sau înlocuiește linkul GitHub; ștergerea lui nu este încă disponibilă.');const saved=await api<Developer>('/me/profile','PATCH',{displayName:v('displayName'),description:v('description'),technologies:limited(split(v('technologies')),20,50,'Tehnologii'),...(v('role')?{role:v('role')}:{}),...(v('availability')?{availability:v('availability')}:{}),...(github?{githubUrl:github}:{}),...(v('experienceYears')?{experienceYears:Number(v('experienceYears'))}:{}),...(v('hourlyRate')?{hourlyRate:Number(v('hourlyRate'))}:{})});d=saved;root.querySelector('[role=status]')!.textContent='Profil salvat.';});return;
 }
 if(path==='/developers'){
  shell(root,'Programatori','Caută colegi după rol, tehnologii și disponibilitate.',`<form class="filters"><div class="field"><label for="filter-role">Rol</label><select id="filter-role" name="role">${options(roles,'','Toate rolurile')}</select></div><div class="field"><label for="filter-tech">Tehnologie</label><input id="filter-tech" name="tech" placeholder="Ex. Spring"></div><div class="field"><label for="filter-availability">Disponibilitate</label><select id="filter-availability" name="availability">${options(availability,'','Oricare')}</select></div><button type="submit" class="auth register">Filtrează</button></form><div id="people" aria-live="polite"></div>`);
  const form=root.querySelector<HTMLFormElement>('form')!;const list=root.querySelector<HTMLElement>('#people')!;let request=0;
  const load=async(page=0)=>{const version=++request;list.innerHTML=skeleton(6,'Se încarcă programatorii…');const params=new URLSearchParams({page:String(page),size:'12'});new FormData(form).forEach((v,k)=>{if(String(v).trim())params.set(k,String(v).trim());});try{const result=await api<Page<Developer>>(`/developers?${params}`);if(!root.isConnected||version!==request)return;list.innerHTML=result.content.length?`<p class="hint">${result.totalElements} profiluri</p><div class="dev-grid">${result.content.map(devCard).join('')}</div><div class="pagination"><button id="prev" class="auth login" ${page===0?'disabled':''}>Înapoi</button><span>Pagina ${page+1} din ${result.totalPages}</span><button id="next" class="auth login" ${page+1>=result.totalPages?'disabled':''}>Înainte</button></div>`:'<div class="empty"><strong>Nu am găsit profiluri</strong><p>Schimbă filtrele sau <a href="/profile">completează-ți profilul</a> ca să apari în căutări.</p></div>';list.querySelector('#prev')?.addEventListener('click',()=>void load(page-1));list.querySelector('#next')?.addEventListener('click',()=>void load(page+1));}catch(e){if(version===request)failure(list,e,()=>void load(page));}};form.addEventListener('submit',e=>{e.preventDefault();void load();});await load();return;
 }
 if(/^\/developers\/\d+$/.test(path)){const d=await api<Developer>(path);if(!root.isConnected)return;document.title=`${d.displayName||'Profil programator'} — MicroCrew`;shell(root,d.displayName||'Profil',roles[d.role||'']||'Client',`<a class="back-link" href="/developers">Înapoi la programatori</a>${devCard(d)}<p class="prose">${escape(d.description||'Nu a fost adăugată o descriere.')}</p>${d.githubUrl&&/^https:\/\/github\.com\//.test(d.githubUrl)?`<a class="auth login" href="${escape(d.githubUrl)}" target="_blank" rel="noopener noreferrer">Profil GitHub</a>`:''}`);return;}
 if(path==='/projects/new'){
  const d=draft;shell(root,'Un proiect nou','Verifică cerințele și salvează proiectul pentru a găsi o echipă.',`<form class="editor">${field('Titlu','title','','required maxlength="150"')}${area('Descriere','description',d?.description,'required minlength="20" maxlength="5000"')}${area('Rezumat','summary',d?.summary,'maxlength="1000"')}<fieldset><legend>Roluri necesare</legend><div class="role-choices">${Object.entries(roles).map(([v,t])=>`<label><input type="checkbox" name="roles" value="${v}" ${d?.roles.includes(v)?'checked':''}> ${t}</label>`).join('')}</div></fieldset>${area('Sarcini, câte una pe linie','tasks',d?.tasks.join('\n'))}${field('Tehnologii existente, separate prin virgulă','existingStack',d?.existingStack.join(', '))}${field('Tehnologii căutate, separate prin virgulă','requiredTechnologies',d?.existingStack.join(', '))}${field('Tarif maxim (dolari pe oră) per programator (opțional)','maxHourlyRate','','type="number" min="0" max="99999999.99" step="0.01"')}<p class="hint">Tariful este în dolari pe oră (USD). Lasă tariful gol dacă nu ai o limită.</p><button type="submit" class="auth register">Salvează și găsește echipa</button><p role="status" aria-live="polite"></p></form>`);
  bindForm(root,async f=>{const v=(n:string)=>String(f.get(n)||'').trim();const selected=f.getAll('roles').map(String);if(!selected.length)throw new Error('Alege cel puțin un rol.');const p=await api<Project>('/projects','POST',{title:v('title'),description:v('description'),summary:v('summary'),roles:selected,tasks:limited(v('tasks').split('\n').map(s=>s.trim()).filter(Boolean),20,500,'Sarcini'),existingStack:limited(split(v('existingStack')),20,100,'Tehnologii existente'),requiredTechnologies:limited(split(v('requiredTechnologies')),20,50,'Tehnologii căutate'),maxHourlyRate:v('maxHourlyRate')?Number(v('maxHourlyRate')):null});draft=null;navigate(`/projects/${p.id}`);});return;
 }
 if(path==='/projects'){
  shell(root,'Proiectele mele','Proiectele tale și cele în care colaborezi.',`<div class="page-actions"><a class="auth register" href="/projects/new">Creează proiect</a><a class="auth login" href="/invitations">Vezi invitațiile</a></div><div id="projects" aria-live="polite"></div>`);const list=root.querySelector<HTMLElement>('#projects')!;
  const load=async(page=0)=>{list.innerHTML=skeleton(3,'Se încarcă proiectele…');try{const data=await api<Page<Project>>(`/projects?page=${page}&size=12&sort=id,desc`);if(!root.isConnected)return;list.innerHTML=data.content.length?data.content.map(p=>`<article class="person"><div><h3><a href="/projects/${p.id}">${escape(p.title)}</a></h3><p>${escape(p.summary||p.description)}</p><div class="tags">${p.roles.map(r=>`<span>${escape(roles[r]||r)}</span>`).join('')}</div></div><span class="hint">${p.ownerId===currentUser()?.id?'Proprietar':'Colaborator'}</span></article>`).join('')+`<div class="pagination"><button id="prev" class="auth login" ${page===0?'disabled':''}>Înapoi</button><span>Pagina ${page+1} din ${data.totalPages}</span><button id="next" class="auth login" ${page+1>=data.totalPages?'disabled':''}>Înainte</button></div>`:'<div class="empty"><strong>Nu ai încă proiecte</strong><p>Descrie o idee pe <a href="/">pagina principală</a>, <a href="/projects/new">creează un proiect</a> sau verifică <a href="/invitations">invitațiile primite</a>.</p></div>';list.querySelector('#prev')?.addEventListener('click',()=>void load(page-1));list.querySelector('#next')?.addEventListener('click',()=>void load(page+1));}catch(e){failure(list,e,()=>void load(page));}};await load();return;
 }
 shell(root,'Pagina nu există','Revino la proiectele tale.','<a class="auth register" href="/projects">Proiecte</a>');
}catch(e){failure(root,e,()=>void renderBasic(root,path,navigate));}}
