export const roles: Record<string, string> = { frontend:'Frontend',backend:'Backend','full-stack':'Full-stack',mobile:'Mobile',devops:'DevOps',qa:'QA / testare',data:'Date',security:'Securitate' };
export const availability: Record<string,string> = { available:'Disponibil','partially-available':'Parțial disponibil',unavailable:'Indisponibil' };
export function escape(value: unknown): string { return String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]!); }
export const options = (values: Record<string,string>,selected='',blank='Alege') => `<option value="">${blank}</option>${Object.entries(values).map(([v,t])=>`<option value="${v}" ${v===selected?'selected':''}>${escape(t)}</option>`).join('')}`;
export const field = (label:string,name:string,value:unknown='',attributes='') => `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" value="${escape(value)}" ${attributes}></div>`;
export const area = (label:string,name:string,value:unknown='',attributes='') => `<div class="field"><label for="${name}">${label}</label><textarea id="${name}" name="${name}" rows="4" ${attributes}>${escape(value)}</textarea></div>`;
export const split = (value:string) => [...new Set(value.split(/[\n,]/).map(v=>v.trim()).filter(Boolean))];
export function limited(values:string[],count:number,length:number,label:string) { if(values.length>count||values.some(v=>v.length>length)) throw new Error(`${label}: maximum ${count} valori, fiecare de cel mult ${length} caractere.`); return values; }
export function shell(root:HTMLElement,title:string,description:string,content:string) { root.innerHTML=`<section class="app-page"><header class="page-heading"><div><h1>${escape(title)}</h1><p>${escape(description)}</p></div></header>${content}</section>`; }
export function bindForm(root:HTMLElement,save:(data:FormData)=>Promise<void>) { const form=root.querySelector<HTMLFormElement>('form')!; form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector<HTMLButtonElement>('[type=submit]')!; const status=form.querySelector<HTMLElement>('[role=status]')!;if(button.disabled||!form.reportValidity())return;button.disabled=true;status.textContent='Se salvează…';try{await save(new FormData(form));}catch(error){status.textContent=error instanceof Error?error.message:'Salvarea a eșuat.';}finally{button.disabled=false;}}); }
